repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: buf-lint
        name: buf lint
        entry: buf lint
        language: system
        types: [proto]
        pass_filenames: false
      - id: buf-format
        name: buf format
        entry: buf format -w
        language: system
        types: [proto]
        pass_filenames: false
      - id: buf-breaking
        name: buf breaking
        entry: buf breaking --against '.git#branch=main'
        language: system
        types: [proto]
        pass_filenames: false
