name: Buf PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - 'proto/**'
      - 'buf.yaml'
      - 'buf.gen.yaml'
      - '.github/workflows/buf-pr-checks.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  buf-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch full history for breaking change detection
          fetch-depth: 0

      - name: Buf lint, format, breaking, and generate check
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          push: false
          # Compare against the pull request's base branch in Git.
          # This is more robust than comparing against the BSR, as it avoids
          # issues with synchronization delays between the main branch and the BSR.
          breaking_against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.base_ref }}'
