name: Buf BSR Push on Release

on:
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: write

jobs:
  buf-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buf push to BSR with release label
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
